# -*- coding: utf-8 -*-
"""statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hdt5srYb8Z1045JcoacXbq8y2yixuaAz

# Statistics
"""

## Interval Estimation

# Library
import pandas as pd
import numpy as np
from scipy.stats import t

# Make sample
samples = pd.Series([9.0, 9.1, 8.8, 9.1, 9.0, 9.4, 9.2, 8.8, 8.6])
print('Samples = ' + str(samples.get_values().tolist()))

# sample mean & standard deviation
mu = samples.mean()
s = samples.std()
print("sample mean is {:.1f}".format(mu))
print("sample standard deviation is {:.2f}".format(s))

# t statistics
n = len(samples)
df = n - 1   # degree of freedom (n-1)
tstatVal = t.ppf(1-0.025, df)
print("t statistics is {:.3f}".format(tstatVal))

# confidence interval
sx = s / np.sqrt(n)
print("confidence interval is ({:.2f} ~ {:.2f})".format(mu-tstatVal*sx, mu+tstatVal*sx))